### ISSUE TITLE
thamos advise: Waiting for response from Thoth

### ISSUE THREAD

**Issue by CermakM** [thoth-station/thamos#116] opened 2019-03-18 14:28 UTC
**Describe the bug**
Following the instructions from [Google Docs](https://docs.google.com/document/d/1QflQpGXtOuHFFC2hkEFBlu0JmCQWEnXdgryvwxCNXpQ/edit)

```
$ pip3 install --user thamos
$ git clone https://github.com/thoth-station/thamos
$ cd thamos/examples/lockdown # contains .thoth.yaml
$ thamos advise
```

Getting stuck at

```
2019-03-18 15:20:30,388 [16158] INFO     thamos: No Pipfile.lock found
2019-03-18 15:20:31,350 [16158] WARNING  thamos.config: Using insecure connection to API service, please contact service provider to install TLS in order to secure network traffic
2019-03-18 15:20:31,915 [16158] INFO     thamos.lib: Successfully submitted advise analysis 'adviser-2d5444d1e496bb8c'
🕒  Waiting for response from Thoth (analysis: adviser-2d5444d1e496bb8c)...
```

**To Reproduce**
Follow the documented steps.

**Expected behavior**
I receive thamos advice.

**Additional context**
<details>
<summary> Version information </summary>

```
$ thamos --version
0.3.0
```

```
$ python --version
Python 3.6.6
```

```
$ pipenv --version
pipenv, version 2018.11.26
```
</details>

**Comment by fridex** [comment] 2019-03-19 15:32
The issue is in operators - for some reason they stop receiving cluster events (cca each hour). I've re-configured deployment to re-start operators each 30 minutes. Let's keep this open until we fix the issue (maybe issue in specific Python's kubernetes/openshift-rest-client library).

**Comment by fridex** [comment] 2019-07-03 13:19
I will close this, this should be resolved already. Feel free to re-open if that's not the case.

**Closed by fridex** 2019-07-03 13:19 UTC
Labels: bug, good first issue
