### ISSUE TITLE
some warning might confuse users

### ISSUE THREAD

**Issue by goern** [thoth-station/thamos#851] opened 2021-05-01 19:12 UTC
**Describe the bug**
when running thamos it logs: `/home/goern/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
` which might confuse users.

**To Reproduce**
1. thamos version 
/home/goern/.local/lib/python3.9/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (4.0.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Thamos Client version: 1.18.1
Thoth API https://khemenu.thoth-station.ninja/api/v1: 0.24.3

/kind feature

**Comment by fridex** [comment] 2021-05-03 06:45
This looks like a broken Python environment. How can I replicate this? Is it toolobox?

**Comment by fridex** [comment] 2021-06-03 13:39
Closing, feel free to reopen. This is caused by a broken environment when installed packages are not respecting the dependency graph. A fix should be to reinstall urllib3/chardet or check dependencies installed (`pip feeze`).

/close

**Closed by fridex** 2021-06-03 13:39 UTC
Labels: kind/feature
